=== mlinke-ai/kev.in/examples/exercises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="kev.in:exercises" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="kev.in:exercises"
    elementFormDefault="qualified">
    <!-- a gab is an element with only a `correct` attribute-->
    <xs:element name="gap">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="correct" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <!-- an error is an element which points out a bug and the correct code-->
    <xs:element name="error">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="value" />
                    <xs:attribute type="xs:string" name="correct" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <!-- text is just a string-->
    <xs:element name="text" type="xs:string" />
    <!-- a line consists of text and gaps-->
    <xs:element name="line">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element ref="text" />
                <xs:element ref="gap" />
                <xs:element ref="error" />
            </xs:choice>
            <xs:attribute name="indentation" type="xs:nonNegativeInteger" default="0" />
            <xs:attribute name="comment" type="xs:boolean" default="false" />
        </xs:complexType>
    </xs:element>
    <!-- line breaks are empty elements-->
    <xs:element name="line-break" type="xs:string" />
    <!-- a code block consists of lines and line breaks-->
    <xs:element name="code-block">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="line" />
                <xs:element ref="line-break" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <!-- puzzle pieces are the building blocks for parsons puzzles-->
    <xs:element name="puzzle-piece">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="code-block" />
            </xs:sequence>
            <xs:attribute type="xs:nonNegativeInteger" name="order" />
        </xs:complexType>
        <xs:unique name="unique-order">
            <xs:selector xpath="puzzle-piece" />
            <xs:field xpath="@order" />
        </xs:unique>
    </xs:element>
    <!-- there are seven possible exercise types-->
    <xs:simpleType name="exercise-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="syntax" />
            <xs:enumeration value="parsons-puzzle" />
            <xs:enumeration value="find-the-bug" />
            <xs:enumeration value="gap-text" />
            <xs:enumeration value="documentation" />
            <xs:enumeration value="output" />
            <xs:enumeration value="programming" />
        </xs:restriction>
    </xs:simpleType>
    <!-- there are two possible langauges-->
    <xs:simpleType name="language">
        <xs:restriction base="xs:string">
            <xs:enumeration value="python" />
            <xs:enumeration value="java" />
        </xs:restriction>
    </xs:simpleType>
    <!-- an exercise consists of one or more code blocks, a solution and test cases-->
    <xs:element name="exercise">
        <xs:complexType>
            <xs:choice>
                <xs:choice>
                    <xs:element ref="code-block" />
                </xs:choice>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element ref="puzzle-piece" />
                </xs:choice>
            </xs:choice>
            <xs:attribute type="exercise-type" name="type" />
            <xs:attribute type="language" name="language" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mlinke-ai/kev.in/examples/programming.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="programming" language="python">
    <code-block>
        <line>
            <text>def adjacent_element_product(array):</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>return # max product</text>
        </line>
        <line-break />
    </code-block>
</exercise>

=== mlinke-ai/kev.in/examples/parsons_puzzle.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="parsons-puzzle" language="python">
    <puzzle-piece order="0">
        <code-block>
            <line comment="true">
                <text># initialize the variables</text>
            </line>
            <line>
                <text>rain = [0,5,1,0,-1,6,7,-2,0]</text>
            </line>
            <line-break />
            <line>
                <text>sumRain = 0</text>
            </line>
            <line-break />
            <line>
                <text>count = 0</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="1">
        <code-block>
            <line comment="true">
                <text># loop through the values in the list</text>
            </line>
            <line>
                <text>for day in rain:</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="2">
        <code-block>
            <line indentation="1" comment="true">
                <text># if the value of the day is positive</text>
            </line>
            <line indentation="1">
                <text>if day >= 0:</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="3">
        <code-block>
            <line indentation="2" comment="true">
                <text># add day to the sum</text>
            </line>
            <line-break />
            <line indentation="2" comment="true">
                <text># also add one to count</text>
            </line>
            <line-break />
            <line indentation="2">
                <text>sumRain = sumRain + day</text>
            </line>
            <line-break />
            <line indentation="2">
                <text>count = count + 1.0</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="4">
        <code-block>
            <line indentation="1" comment="true">
                <text># otherwise</text>
            </line>
            <line-break />
            <line indentation="1" comment="true">
                <text>else:</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="5">
        <code-block>
            <line indentation="2" comment="true">
                <text># print no rain</text>
            </line>
            <line-break />
            <line indentation="2">
                <text>print("No rain")</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="6">
        <code-block>
            <line comment="true">
                <text># if count is positive</text>
            </line>
            <line-break />
            <line>
                <text>if count > 0:</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
    <puzzle-piece order="7">
        <code-block>
            <line indentation="1" comment="true">
                <text># calculate and print the average</text>
            </line>
            <line-break />
            <line indentation="1">
                <text>ave = sumRain / count</text>
            </line>
            <line-break />
            <line indentation="1">
                <text>print("Average",ave)</text>
            </line>
            <line-break />
        </code-block>
    </puzzle-piece>
</exercise>

=== mlinke-ai/kev.in/examples/docuementation.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="documentation" language="python">
    <code-block>
        <line>
            <text>import math</text>
        </line>
        <line-break />
        <line>
            <text>class Circle():</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>def __init__(self, radius):</text>
        </line>
        <line-break />
        <line indentation="2">
            <text>self.radius = radius</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>def get_circumference(self):</text>
        </line>
        <line-break />
        <line indentation="2">
            <text>return 2 * math.pi * self.radius</text>
        </line>
        <line-break />
    </code-block>
</exercise>

=== mlinke-ai/kev.in/examples/find_the_bug.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="find-the-bug" language="python">
    <code-block>
        <line>
            <text>x = 0</text>
        </line>
        <line-break />
        <line>
            <text>total = 0</text>
        </line>
        <line-break />
        <line>
            <text>while x &lt; 100:</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>total += x</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>x </text>
            <error value="=" correct="+=" />
            <text> 1</text>
        </line>
    </code-block>
</exercise>

=== mlinke-ai/kev.in/examples/syntax.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="syntax" language="python">
    <code-block>
        <line>
            <text>a = 3</text>
        </line>
        <line-break />
        <line>
            <text>print(a)</text>
        </line>
        <line-break />
    </code-block>
</exercise>

=== mlinke-ai/kev.in/examples/gap_text.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="gap-text" language="python">
    <code-block>
        <line>
            <text>num1 = 10</text>
        </line>
        <line-break />
        <line>
            <text>num2 = 100</text>
        </line>
        <line-break />
        <line>
            <text>total = </text>
            <gap correct="num1 + num2" />
        </line>
        <line-break />
        <line>
            <text>print(num1, "+", num2, "=", total)</text>
        </line>
    </code-block>
</exercise>

=== mlinke-ai/kev.in/examples/output.xml
<?xml version="1.0" encoding="UTF-8"?>
<exercise xmlns="kev.in:exercises" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="kev.in:exercises exercises.xsd"
    type="output" language="python">
    <code-block>
        <line>
            <text>def convert_celsius_to_fahrenheit(temperature):</text>
        </line>
        <line-break />
        <line indentation="1" comment="true">
            <text># Temperature time 9/5, plus 32</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>fahren = temperature * (9/5)</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>fahren += 32</text>
        </line>
        <line-break />
        <line indentation="1">
            <text>return fahren</text>
        </line>
        <line-break />
        <line>
            <text>temp = 33</text>
        </line>
        <line-break />
        <line>
            <text>fahren = convert_celsius_to_fahrenheit(temp)</text>
        </line>
        <line-break />
        <line>
            <text>print(temp, "degrees C is", fahren, "degrees F")</text>
        </line>
        <line-break />
    </code-block>
</exercise>
